### ISSUE TITLE
Harassment by another member of the community

### ISSUE THREAD

**Issue by JJ** [perl6/problem-solving#131] opened 2019-11-23 16:14 UTC
I would like ot report abusive behavior by @ugexe using insults and expletives directed to another member of the community, that would be me.

This has been happening for a long time, and I've tried to just bear with it and keep on doing my best.
However, I draw the line [here](https://github.com/hoelzro/p6-linenoise/pull/30#issuecomment-557801372). You can follow pretty much the whole interchange in that PR, as well as [here](https://github.com/rakudo/star/pull/144#issuecomment-557793383)

Using words like "do nonsense" and "fucking things up" directed to another member of the community is not something we should bear with. I feel deeply offended, even more so when this is a continued pattern of behavior that goes back at least 1 year. His comments are almost always abusive (also almost always right), but never constructive or helpful.

We don't have a comprehensive code of conduct for the whole community, so I couldn't think of any other way to bring this up. This is for problem solving, so I guess that's the way to go.

**Comment by AlexDaniel** [comment] 2019-11-23 17:39
I asked @lizmat to take care of this ticket because I'm clearly not a role model when it comes to issues like this. I hope we can resolve this peacefully.

**Comment by lizmat** [comment] 2019-11-23 20:35
I've chatted with ugexe in private, have not done so yet with JJ.  Since I'm still definitely not working on all cylinders, I'm calling it a day for now.  Will try to chat with JJ tomorrow.

**Comment by lizmat** [comment] 2019-11-25 08:53
A headsup: I've chatted with JJ and ugexe yesterday and am mulling on how to go forward on this.  But first I will need to do the Rakudo Weekly today.

**Comment by tony-o** [comment] 2019-11-25 22:10
This does not seem like the right forum to handle personal grievances.

**Comment by AlexDaniel** [comment] 2019-11-25 22:19
@tony-o well, we don't have any proper place to resolve such issues, I think? Also, I personally feel like there is sometimes tension coming from the way developers interact with each other (I'm also part of the problem), so doing it in public is perhaps not the worst idea. I hope we can all learn and become better.

But I'd like to know, if this is not the right place, then how should it be done? Maybe this should be discussed as well, so that we can handle it nicer next time.

**Comment by tony-o** [comment] 2019-11-26 00:20
It's my 2¢ that this kind of thing should be handled directly and in a more real time format than airing grievances for the world and everyone look to hack on raku to see. Has there been an attempt for a hangouts or some kind of face to face?  Has there been a private message in IRC or some other forum?  Has there been an ask from anyone to ugexe to mediate the situation in any more private channels prior to this?

It's great that people want to be nice but part of doing so requires direct communication, even if the situation is untenable and requires a mediator, a problem solving repo is the wrong forum.  It also posits that either JJ or ugexe is a problem (and if it doesn't, then it's invalid to claim that ugexe calling something `fucked up` translates to him calling that person the same, which is what is being said in the main bit of this thread).

I'm not defending either party but it's meaner and, frankly, detrimental to contributors and to the community to let wrong things go unchecked because you're afraid of hurting someone's feelings.  Being wrong is a great method for learning and shouldn't be taken personally.

**Comment by JJ** [comment] 2019-11-26 06:30
El mar., 26 nov. 2019 a las 1:20, tony-o (<notifications@github.com>)
escribió:

> It's my 2¢ that this kind of thing should be handled directly and in a
> more real time format than airing grievances for the world and everyone
> look to hack on raku to see. Has there been an attempt for a hangouts or
> some kind of face to face? Has there been a private message in IRC or some
> other forum? Has there been an ask from anyone to ugexe to mediate the
> situation in any more private channels prior to this?
>
> It's great that people want to be nice but part of doing so requires
> direct communication, even if the situation is untenable and requires a
> mediator, a problem solving repo is the wrong forum. It also posits that
> either JJ or ugexe is a problem (and if it doesn't, then it's invalid to
> claim that ugexe calling something fucked up translates to him calling
> that person the same, which is what is being said in the main bit of this
> thread).
>
> I'm not defending either party but it's meaner and, frankly, detrimental
> to contributors and to the community to let wrong things go unchecked
> because you're afraid of hurting someone's feelings. Being wrong is a great
> method for learning and shouldn't be taken personally.
>
If you consider that is the issue, you are probably part of the problem.





I could have stopped there. Telling you you're wrong, in a harsh way, and
just be done with it, right? If you ask any follow up question about that,
well, "Not my duty to tell you what's the right way to do it", right? If
you simply say that "There are more polite ways to say that, without
getting personal" (because you feel offended because I've told you "you're
part of the problem"), well, I could get back to you saying that my duty is
to call a spade a space, and not "dance around" what you do, couldn't I?

The English language, not being my mother tongue, BTW, is a infinitely
flexible and beautifully nuanced language. Most languages are, BTW. There's
a book by Queneau that's basically 99 (or some such) ways of telling the
same story, in different tones and styles. But let's give this one a try.

* "Excuse me, but I would like to draw your attention to the fact that
reviewing errors and pointing them out is not the problem. The problem is
the way it's done, and also the fact that that criticism is never
constructive and never points in the right direction. So learning might
come eventually, but not through that quipping back"

* "May I point out that you are using the logical argument called a
strawman fallacy. By deviating the attention from the main point, which is
the way criticism is constructed and its main point, you're raising a
strawman "Hey! Look at this person that does not want his work criticised!
Bad person!" and even hinting that might be prejudicial to the community.
That's probably not a good thing"

I could to al the way to... Well, I ain't gonna, because I would become
part of the problem. You probably get the point.

**Comment by nxadm** [comment] 2019-11-26 07:25
> Has there been an attempt for a hangouts or some kind of face to face? Has there been a private message in IRC or some other forum? Has there been an ask from anyone to ugexe to mediate the situation in any more private channels prior to this?

@tony-o, in her role as a mediator, discussing the issue privately is what @lizmat++ has been doing. It's important to give her time to find a solution, and use her experience as pointers on how to handle this in the future.

The "problem-solving" part of the issue here, is because:
- we don't have *any* proper channels to handle this (yet), as @AlexDaniel points out.
- an other reason to use this repo is probably because this may not be solely an interpersonal problem, but also a request for community guidelines on how to communicate.

2c etc.

**Comment by lizmat** [comment] 2019-11-26 11:49
No pressure  :-)

These are *my* views so far.  If you have a problem with them, please blame me :-)

First of all, I believe that both members who are the subject of this issue, only have good intentions towards the Rakudo project.  They are both driven to create value.  Albeit in different ways perhaps: one focused more on technical correctness, the other focusing more on growing the Rakudo community and teaching.

Secondly, the fact that not everybody has the same command of the English language, should not be underestimated.  What one side interpreted as a (negative) comment on the *content* of the action, intended as a (rather blunt) teaching tool, the other side interpreted as an attack on the *person* doing the action.

Thirdly: not everyone is sharing the same sense of urgency in the community.  What one side intended as a way to be supportive of a new member of the Raku community (who appeared to have their PR warnocked, and thus potentially be lost to the Raku community if not addressed in time), was interpreted by the other as an overeager action causing / hiding / not fixing a bug that needed deeper investigation.

I will now return to mulling mode for now.

**Comment by tony-o** [comment] 2019-11-26 16:27
@jj:

> If you consider that is the issue, you are probably part of the problem. I could have stopped there. Telling you you're wrong, in a harsh way, and just be done with it, right?

Yes, then we wouldn't be having an issue and we'd both continue to contribute in the ways we think meaningful.  The difference is yours is of opinion and the matters referenced aren't.  Why would I take any of that statement personally?

@nxadm: 

> @tony-o, in her role as a mediator, discussing the issue privately is what @lizmat++ has been doing. It's important to give her time to find a solution, and use her experience as pointers on how to handle this in the future.

I take no issue with what is being discussed; the manner it's being approached and brought up is passive and the channel is inappropriate.  Creating a github issue because you're taking personal issue with someone is not private.  This has nothing to do with @lizmat or the way she is handling the issue, she's at the mercy of the way this was approached.  The point of the repo is that it's not entirely up to one person, she just happens to be the one asked to mediate in this case.

>     * we don't have _any_ proper channels to handle this (yet), as @AlexDaniel points out.

IRC, where all parties involved are active is more appropriate.  A direct message between parties: also more appropriate.  Email: more appropriate.  Public request for help dealing with a personal offense taken when nothing else has been tried: inappropriate.

>     * an other reason to use this repo is probably because this may not be solely an interpersonal problem, but also a request for community guidelines on how to communicate.

Then, in accordance with the README in this repo the issue should've brought up the request for a code of conduct and not a complaint that someone was technically right but not nice about it.  Perhaps the title of the issue should've reflected that request instead.  The README in this repo reads:

> Anyone is welcome to create a new issue. The ticket should only contain the description of the actual problem (X of the XY). It is advised that you start your ticket with a short description of the problem and include more details afterwards.

This GH issue does not do this.

**Comment by tony-o** [comment] 2019-11-26 16:28
> Secondly, the fact that not everybody has the same command of the English language, should not be underestimated. What one side interpreted as a (negative) comment on the _content_ of the action, intended as a (rather blunt) teaching tool, the other side interpreted as an attack on the _person_ doing the action.

This is probably a rather large part of it.

**Comment by nxadm** [comment] 2019-11-26 17:33
@tony-o, I will respectfully refrain from further commenting on this (sub-) thread, not because of a lack of agreement and/or disagreement, but because I feel we're moving away from the original issue.

**Comment by tony-o** [comment] 2019-11-26 17:42
> @tony-o, I will respectfully refrain from further commenting on this (sub-) thread, not because of a lack of agreement and/or disagreement, but because I feel we're moving away from the original issue.

Perhaps IRC would be a more appropriate place for actual discussion

**Comment by coke** [comment] 2019-11-26 18:52
This particular set of interactions serves as an example of why a Code of Conduct is needed. The larger issue of a CoC requires addressing - even if it is possible for the the two community members to resolve the particular issue cited here, a framework should exist. This is the sort of thing the Raku community can reach out to the TPF board for guidance on.

**Comment by coke** [comment] 2019-11-26 18:58
Regarding TPF, here's the CoC for the latest conference: https://perlconference.us/tpc-2020-hou/standards-of-conduct/ ; Here's the standards for p5porters: https://perldoc.perl.org/perlpolicy.html#STANDARDS-OF-CONDUCT

**Comment by japhb** [comment] 2019-11-26 19:02
We already drafted a Community Code of Conduct; I contributed to it in both [initial brainstorming](https://gist.github.com/japhb/b76f7d3a816df4d65108) and the [drafted form](https://raw.githubusercontent.com/perl6/specs/master/S27-perl-culture-draft.pod6).

Perhaps it is finally time to take a look at that again?

**Comment by ugexe** [comment] 2019-11-26 19:12
Maybe there is a need to discuss a CoC. However it was a mistake for a submitter to appropriate "community" for themselves and to use my name to bring this up. If I were to bring up discussion for how to handle negligent contributors would I be correct in naming individuals?

**Comment by japhb** [comment] 2019-11-26 19:28
(NOTE: I AM NOT TRYING TO WORK AROUND lizmat!  The following is only about separating this case from our general path forward, not the facts and resolution of this *particular case*.)

In the above discussion there seems to be general consensus to at least discuss a SoC/CCoC document, but if I understand you correctly ugexe you're (at least partly) upset that this particular case and the general discussion are mixed together.  I thus propose that we simply create a **new** issue, focused on the general question of SoC/CCoC, procedure for drafting/approving it, and process for handling future cases, and leave *this case* to lizmat's mulling/arbitration/decision.

**Comment by vrurg** [comment] 2019-11-26 19:42
@japhb I think a separate issue on finalizing the CoC draft makes total sense. Would you open one?

**Comment by lizmat** [comment] 2019-11-26 19:55
Re p5porters CoC: "The official forum for the development of perl is the perl5-porters mailing list, mentioned above, and its bugtracker at rt.perl.org."

Since rt.perl.org is dead, I guess this will need to be changed.

**Comment by japhb** [comment] 2019-11-26 20:29
@vrurg: OK, creating one.

**Comment by ugexe** [comment] 2019-11-26 20:56
Well, thanks for re-linking my name to the discussion I guess.

**Comment by Grinnz** [comment] 2019-11-26 20:59
@lizmat thanks, I will work on getting that updated.

**Comment by japhb** [comment] 2019-11-26 20:59
@ugexe: Gah, I forgot that GH issues would do that sometimes-annoying bidirectional linking.  I have edited the above, but I doubt GH's bug will undo itself.  :-(

**Comment by lizmat** [comment] 2019-11-26 22:01
I will get back to this tomorrow.

**Comment by lizmat** [comment] 2019-11-27 17:53
With these remarks I hope to close this issue.

First of all, I would like to thank both Nick Logan as well as JJ Merelo for chatting with me in private to try to resolve this issue.

I'm afraid closing this Github issue will *not* resolve the issues that exist between them: but I hope it will be the start of a better mutual respect for their respective roles in the Raku community.

What this issue made very clear, is that we, as the Raku community, do not currently have a preferred way of solving inter-personal conflicts.  Unfortunately, heading out to a bar for some socializing, is not really an option when you're as geographically dispersed as the Raku community is.

Perhaps starting a #raku-bar IRC channel for strictly relaxing and handling personal issues, would be a way to at least mimic the local bar where you could hang out with your mates (of whatever gender).

Getting back to the cause of the issue: it's become clear to me that the two people involved in this issue, have very different views on how they can contribute / are contributing to the development of Raku in Rakudo.  Which can be explained from their respective backgrounds.  And that these views have caused friction for a number of years already (examples have been provided by both, but will not be repeated here as this is not a trial needing proof for conviction).

Apart from their different views, in a way this is also a clash of cultures.  Which should remind us all that not everybody in the world has grown up in a culture where being blunt to a person is *not* necessarily a judgement of that person.  Some cultures find it very impolite, even not done to use the word "no" or derivatives thereof.  So, please be *more* polite than you would normally be if you're used to being very straightforward.  And please be *more* straightforward if you're used to being very polite.  And realize that what you consider "normal" may be misconstrued by the other side at *any* time.

In the Raku community, well in every on-line community really, we have to realize that the background of the person at the other end, may cause a different interpretation of words said than were intended by the speaker.  This can be hard, because many of us in the Raku community lead a busy life with only so much time to devote to Raku.  And then you want every moment to count.

Please remember we are *all* volunteers, even if you're working on a grant.  You work on a grant because you want some feature implemented and cannot find enough free time to do so.  Not to be making tons of money.

The closing of this ticket will not undo all of the interactions that have happened in the past.  In the age of git and GitHub, all interactions become part of the permanent record.  We have to learn to live with that.  But moving forward I hope that the opponents in this issue, will learn to work together better and learn to appreciate each other's zeal and each other's value in the Raku community.

**Closed by lizmat** 2019-11-27 17:53 UTC
Labels: fallback
